name: Issues Arise Workflow
on: issues

jobs:
  issues:
    runs-on: ubuntu-latest
    steps:
      - name: Printing issue details
        run: echo "The context of the workflow is ${{ toJSON(github) }}"