name: Issues Arise Workflow
on: issues

jobs:
  issues:
    runs-on: ubuntu-latest
    steps:
      - name: Printing issue details
        run: echo "Issue title: ${{ github.event.issue.title }}, Issue body: ${{ github.event.issue.body }}"